coverage:
  precision: 2
  round: down
  range: 90...100

  status:
    project:
      default:
        threshold: 6%
        target: 90%
    patch:
      default:
        enabled: no
ignore:
  - "contracts/vip/.*"
  - "test/.*"
