[workspace]
members  = ["contracts/*"]
resolver = "2"

[workspace.package]
version    = "0.1.0"
edition    = "2021"
homepage   = "https://stargaze.zone"
repository = "https://github.com/public-awesome/core"
license    = "Apache-2.0"

[workspace.dependencies]
sg721-base      = { git = "https://github.com/public-awesome/launchpad.git", branch = "initia", features = ["library"] }
sg721           = { git = "https://github.com/public-awesome/launchpad.git", branch = "initia", features = ["library"] }

cosmwasm-schema  = "1.3.1"
cosmwasm-std     = "1.3.1"
cw-storage-plus  = "1.1.0"
cw2              = "1.1.0"
cw-utils         = "1.0.1"
schemars         = "0.8.11"
serde            = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror        = "1.0.31"

[profile.release]
rpath            = false
lto              = true
overflow-checks  = true
opt-level        = 3
debug            = false
debug-assertions = false
