/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  base_uri: string;
  collection_code_id: number;
  tiers: Uint128[];
}
export type ExecuteMsg = {
  mint: {};
} | {
  update: {
    token_id: number;
  };
} | {
  pause: {};
} | {
  resume: {};
} | {
  update_tiers: {
    tiers: Uint128[];
  };
} | {
  update_base_uri: {
    base_uri: string;
  };
};
export type QueryMsg = {
  collection: {};
} | {
  is_paused: {};
} | {
  token_update_height: {
    token_id: number;
  };
} | {
  tier: {
    address: string;
  };
} | {
  tiers: {};
};
export type String = string;
export type Boolean = boolean;
export type Uint64 = number;
export type ArrayOfUint128 = Uint128[];
