/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  fee_bps: number;
}
export type ExecuteMsg = {
  fair_burn: {
    recipient?: string | null;
  };
};
export type QueryMsg = {
  contract_version: {};
} | {
  config: {};
};
export type Decimal = string;
export interface Config {
  fee_percent: Decimal;
}
export interface ContractVersion {
  contract: string;
  version: string;
}