/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  fee_bps: number;
  fee_manager: string;
}
export type ExecuteMsg = {
  fair_burn: {
    recipient?: string | null;
  };
};
export type QueryMsg = {
  config: {};
};
export type SudoMsg = {
  update_config: {
    fee_bps?: number | null;
    fee_manager?: string | null;
  };
};
export type Addr = string;
export type Decimal = string;
export interface Config {
  fee_manager: Addr;
  fee_percent: Decimal;
}