/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./FairBurn.types";
import * as _1 from "./FairBurn.client";
import * as _2 from "./FairBurn.message-composer";
import * as _3 from "./FairBurn.react-query";
import * as _4 from "./RoyaltyRegistry.types";
import * as _5 from "./RoyaltyRegistry.client";
import * as _6 from "./RoyaltyRegistry.message-composer";
import * as _7 from "./RoyaltyRegistry.react-query";
export namespace contracts {
  export const FairBurn = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
  export const RoyaltyRegistry = { ..._4,
    ..._5,
    ..._6,
    ..._7
  };
}