[package]
name        = "sg-basic-whitelist-derive"
authors     = ["Shane Vitarana <s+git@publicawesome.com>"]
description = "Macros for generating code used by the `sg-basic-whitelist` crate"
version     = { workspace = true }
edition     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

[lib]
doctest    = false # disable doc tests
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote       = "1"
syn         = "1"
