name: E2E Integration Tests

on:
  pull_request:

jobs:
  test:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v1

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install latest nightly toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown

      - name: Rust Dependencies Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            artifacts
          key: ${{ runner.os }}-cargo-with-artifacts-${{ hashFiles('**/Cargo.lock') }}

      - name: Optimize contracts
        run: just optimize

      - name: Optimized Contracts Cache
        uses: actions/cache@v3
        with:
          path: |
            target/
          key: ${{ runner.os }}-cargo-with-artifacts-${{ hashFiles('contracts/**') }}

      - name: Run e2e tests for loyalty program contracts
        run: just e2e-test-loyalty-program
